export const PLUGIN_NAME = 'SmartImpact Figma Quick Edit Variables'
export const SETTINGS_PLUGIN_DATA_KEY = 'settings'
export const SETTINGS_SCHEMA_VERSION = 1
export const DEFAULT_WINDOW_SIZE = { width: 420, height: 640 }
export const MIN_WINDOW_SIZE = { width: 360, height: 420 }
export const MAX_WINDOW_SIZE = { width: 900, height: 1000 }
export const WINDOW_SIZE_STORAGE_KEY = 'window-size-v1'
export const ACTIVE_TAB_STORAGE_KEY = 'active-tab-v1'
export const DIFF_CODE_PREFS_STORAGE_KEY = 'diff-code-preferences-v1'
export const DEFAULT_DIFF_CODE_PANEL_HEIGHT = 220
export const MIN_DIFF_CODE_PANEL_HEIGHT = 120
export const MAX_DIFF_CODE_PANEL_HEIGHT = 420
